### ISSUE TITLE
profile views

### ISSUE THREAD

**Issue by kambleaa007** [myDeveloperJourney/myDeveloperJourney#1]
for every refresh from same machine, i have seen profile views getting incremented,
not a big issue at all,
its maybe work as expected,
just want, you to know!!! 

Thanks,
Ashish

**Comment by myDeveloperJourney** [comment]
Hey @kambleaa007, thank you for pointing this out. Are you able to issue a PR with a solution to resolve this issue?

**Comment by kambleaa007** [comment]
Hey, its not possible (as there is something github proxy),
others had encountered the same,
here you can find more details,

https://github.com/antonkomarev/github-profile-views-counter/issues/15
He is working on to fix,
https://rahuldkjain.github.io/gh-profile-readme-generator/about

**Comment by myDeveloperJourney** [comment]
Thank you @kambleaa007! ✌️
